### PR TITLE
Fix grpc/datastore tests

### PR DESCRIPTION
**Pull request by jonasfj**

### CODE REVIEW

**Comment by jonasfj** [comment]
There is still a timeout, but at least this fixed most of the test cases :)
```
[appengine]$pub run test
00:35 +27: test/integration/grpc_datastore_test.dart: e2e_datastore empty_commit negative_empty_commit_xg
  Skip: Existing failure
01:12 +29 ~1 -1: test/integration/grpc_datastore_test.dart: e2e_datastore query query [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test_api  Invoker._onRun.<fn>.<fn>.<fn>

01:40 +39 ~1 -1: Some tests failed.
[appengine]$
```

**Comment by jonasfj** [comment]
Fixed the last test by bumping the timeout...
```
[appengine]$pub run test
00:37 +27: test/integration/grpc_datastore_test.dart: e2e_datastore empty_commit negative_empty_commit_xg
  Skip: Existing failure
01:44 +40 ~1: All tests passed!
[appengine]$
```

**Comment by domesticmouse** [comment]
QQ, do you think this will fix https://github.com/dart-lang/appengine/issues/123?

**Comment by jonasfj** [comment]
Doubtful, this only touches the test files :)

**Pull request merged**
