### PR TITLE
Run dartfmt on appengine

### PR DESCRIPTION
**Pull request by jcollins-g**
I think this is mostly an improvement?

### CODE REVIEW

**Comment by mit-mit** [comment]
@jcollins-g do you agree?

If so, it should simply be a matter of creating a two-line travis file:
https://docs.travis-ci.com/user/languages/dart#formatter

**Comment by kevmoo** [comment]
Travis is already enabled – just needs a `.travis.yml` file

**Comment by kevmoo** [comment]
https://travis-ci.org/dart-lang/appengine

**Comment by mkustermann** [comment]
There is a little more to do I suppose because the end2end test need a service account to be able to work.

**Comment by mit-mit** [comment]
Initially (to get this PR landed) we can just add the format check. Actually running tests in travis sounds like a good improvement, but separate from the current issue.

**Comment by kevmoo** [comment]
What Michael said!

**Comment by jonasfj** [comment]
This looks like an improvement, I'll take it :)

**Pull request merged**
