### PR TITLE
add a CI; rev version in prep for publishing

### PR DESCRIPTION
**Pull request by devoncarew**
- add a CI configuration
- rev the package version in prep for publishing
- address several analysis issues
- add std markdown badges

### CODE REVIEW

**Comment by devoncarew** [comment]
@jonasfj, @kevmoo - I see this failure when trying to enable `dart test` for this repo:

```
test/integration/grpc_datastore_test.dart (failed)
  Failed to load "test/integration/grpc_datastore_test.dart": Environment variables E2E_TEST_PROJECT and E2E_TEST_KEY required when not running on the package bot
```

Should I disable that test?

**Comment by kevmoo** [comment]
We should be able to put those in secrets...or something....

Are they failing NOW? If so, maybe we can leave them failing... 🤷

**Comment by devoncarew** [comment]
I'm adding CI to this package; they're failing locally as well (as I also don't have the `E2E_TEST_PROJECT`, ... env vars defined).

**Comment by devoncarew** [comment]
Nevermind - I see the issue.

**Comment by kevmoo** [comment]
@jonasfj – you should approve this. I don't use this package any more 😄

**Review by jonasfj — APPROVED** [review]

**Comment by jonasfj** [comment]
We could setup testing, but we have to get some exemptions to be able to export service account keys... I built it so that we can test locally using application-default-credentials, which is what I do.

**Pull request merged**
