### PR TITLE
Include more standard logging, prepare for release

### PR DESCRIPTION
**Pull request by kevmoo**
Inspired by this Java code - https://github.com/GoogleCloudPlatform/google-cloud-java/blob/4c004858f1999665e368d9e6a25a24287ef3d741/google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java#L199

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @isoos – turns out there's a "right" way to handle `X-Cloud-Trace-Context`

**Comment by isoos** [comment]
And pub site will pick this up automatically, right?

**Comment by kevmoo** [comment]
> And pub site will pick this up automatically, right?

Yup. And we can get rid of most of this - 
https://github.com/dart-lang/pub-dartlang-dart/blob/master/app/lib/shared/trace_context.dart

**Comment by kevmoo** [comment]
@mkustermann – PTAL

**Pull request merged**
