### PR TITLE
Implement `onConnectionStateChanged` to sync grpc upstream

### PR DESCRIPTION
**Pull request by keyonghan**
Fixes: https://github.com/dart-lang/appengine/issues/154

### CODE REVIEW

**Review by devoncarew — COMMENTED** [review]
Thanks! Can you update the package version in the pubspec to `0.13.4` to match the changelog change, and rev the dep on `grpc` to `^3.1.0` to reflect that we now depend on that version?

**Comment by keyonghan** [comment]
> Thanks! Can you update the package version in the pubspec to 0.13.4 to match the changelog change, and rev the dep on grpc to ^3.1.0 to reflect that we now depend on that version?

Oops, missed that. Updated.

**Review by devoncarew — APPROVED** [review]
👍

**Comment by keyonghan** [comment]
@devoncarew How is the release process like? Wondering when the new version will be populated to pub.dev.

**Comment by devoncarew** [comment]
> How is the release process like? Wondering when the new version will be populated to pub.dev.

It's currently manual; I just published a new version (w/ this change).

**Pull request merged**
